spring.application.name=tamales-lechona-api

# BD Neon
spring.datasource.url=${DB_URL:jdbc:postgresql://ep-calm-fire-b5y4pcy1-pooler.c-7.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require} 
spring.datasource.username=${DB_USERNAME:neondb_owner}
spring.datasource.password=${DB_PASSWORD:}

spring.jpa.hibernate.ddl-auto=update

# Swagger UI: http://localhost:8080/swagger-ui.html
springdoc.swagger-ui.path=/swagger-ui.html

# Umbral usado por el observer AlertaStock para avisar cuando el stock queda bajo
inventario.stock-minimo=5
