package view;

import controller.PedidoController; import controller.ProductoController; import controller.UsuarioController; import model.*; import pagos.AdaptadorPagoWompi; import pagos.ProcesadorPago;
import javax.swing.*; import javax.swing.table.DefaultTableModel; import java.awt.*; import java.math.BigDecimal; import java.net.URI; import java.time.format.DateTimeFormatter; import java.util.*;

/** Flujo completo: cliente -> productos -> resumen -> crear pedido -> pagar. */
public class PedidoPanel extends JPanel {
    private static final DateTimeFormatter F=DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm"); private final UsuarioController usuarios;
    private final JComboBox<Cliente> cliente=new JComboBox<>(); private final JComboBox<Producto> producto=new JComboBox<>(); private final JSpinner cantidad=new JSpinner(new SpinnerNumberModel(1,1,10000,1));
    private final JComboBox<MetodoPago> metodo=new JComboBox<>(MetodoPago.values()); private final JTextField direccion=new JTextField(25); private final JLabel total=new JLabel("Total: $0");
    private final DefaultTableModel carritoModel=new DefaultTableModel(new Object[]{"Producto","Cantidad","Precio unitario","Subtotal"},0){public boolean isCellEditable(int r,int c){return false;}}; private final JTable carrito=new JTable(carritoModel);
    private final DefaultTableModel pedidosModel=new DefaultTableModel(new Object[]{"ID","Cliente","Total","Estado","Pago","Método","Fecha"},0){public boolean isCellEditable(int r,int c){return false;}}; private final JTable pedidos=new JTable(pedidosModel);
    private final Map<Integer,DetallePedido> detalles=new LinkedHashMap<>();
    public PedidoPanel(UsuarioController usuarios){this.usuarios=usuarios;setLayout(new BorderLayout(12,12));setBorder(BorderFactory.createEmptyBorder(12,12,12,12));
        cliente.setRenderer(rendererCliente()); producto.setRenderer(rendererProducto());
        JPanel cab=new JPanel(new GridBagLayout());cab.setBorder(BorderFactory.createTitledBorder("1. Preparar pedido"));GridBagConstraints g=new GridBagConstraints();g.insets=new Insets(4,4,4,4);g.fill=GridBagConstraints.HORIZONTAL;
        add(cab,g,0,"Cliente:",cliente);add(cab,g,1,"Producto:",producto);add(cab,g,2,"Cantidad:",cantidad);add(cab,g,3,"Dirección de entrega:",direccion);add(cab,g,4,"Método de pago:",metodo);
        JPanel addRow=new JPanel(new FlowLayout(FlowLayout.LEFT));JButton agregar=new JButton("Agregar al pedido");JButton quitar=new JButton("Quitar seleccionado");JButton crear=new JButton("Crear pedido");JButton pagar=new JButton("Generar pago Wompi");addRow.add(agregar);addRow.add(quitar);addRow.add(crear);addRow.add(pagar);addRow.add(total);g.gridx=0;g.gridy=5;g.gridwidth=2;cab.add(addRow,g);
        JPanel resumen=new JPanel(new BorderLayout(5,5));resumen.setBorder(BorderFactory.createTitledBorder("Resumen del pedido"));resumen.add(new JScrollPane(carrito),BorderLayout.CENTER);
        JTabbedPane centro=new JTabbedPane();centro.addTab("Nuevo pedido",resumen);centro.addTab("Pedidos registrados",new JScrollPane(pedidos));
        add(cab,BorderLayout.NORTH);add(centro,BorderLayout.CENTER);
        agregar.addActionListener(e->agregarProducto());quitar.addActionListener(e->quitarProducto());crear.addActionListener(e->crearPedido(centro));pagar.addActionListener(e->pagarWompi());cliente.addActionListener(e->cargarDireccion());
        pedidos.getSelectionModel().addListSelectionListener(e->{});refrescarClientes();refrescarProductos();refrescarTabla();
    }
    private DefaultListCellRenderer rendererCliente(){return new DefaultListCellRenderer(){public Component getListCellRendererComponent(JList<?> l,Object v,int i,boolean s,boolean f){super.getListCellRendererComponent(l,v,i,s,f);if(v instanceof Cliente c)setText(c.getNombre()+" "+c.getApellido());return this;}};}
    private DefaultListCellRenderer rendererProducto(){return new DefaultListCellRenderer(){public Component getListCellRendererComponent(JList<?> l,Object v,int i,boolean s,boolean f){super.getListCellRendererComponent(l,v,i,s,f);if(v instanceof Producto p)setText(p.getNombre()+" · $"+p.getPrecio());return this;}};}
    private void add(JPanel p,GridBagConstraints g,int y,String l,JComponent c){g.gridy=y;g.gridx=0;g.gridwidth=1;g.weightx=0;p.add(new JLabel(l),g);g.gridx=1;g.weightx=1;p.add(c,g);}
    private void cargarDireccion(){Cliente c=(Cliente)cliente.getSelectedItem();if(c!=null&&direccion.getText().isBlank())direccion.setText(c.getDireccion());}
    private void agregarProducto(){Producto p=(Producto)producto.getSelectedItem();if(p==null){aviso("No hay productos disponibles.");return;}int q=(Integer)cantidad.getValue();if(!p.consultarDisponibilidad(q)){aviso("No hay stock suficiente para esa cantidad.");return;}DetallePedido d=detalles.get(p.getIdProducto());if(d==null)detalles.put(p.getIdProducto(),new DetallePedido(p,q,p.getPrecio().doubleValue()));else d.setCantidad(d.getCantidad()+q);refrescarCarrito();}
    private void quitarProducto(){int r=carrito.getSelectedRow();if(r<0)return;String name=(String)carritoModel.getValueAt(r,0);Producto found=ProductoController.buscarProducto(name);if(found!=null)detalles.remove(found.getIdProducto());refrescarCarrito();}
    private void refrescarCarrito(){carritoModel.setRowCount(0);double t=0;for(DetallePedido d:detalles.values()){double sub=d.calcularSubtotal();t+=sub;carritoModel.addRow(new Object[]{d.getProducto().getNombre(),d.getCantidad(),d.getPrecioUnitario(),sub});}total.setText(String.format("Total: $%,.0f",t));}
    private void crearPedido(JTabbedPane tabs){Cliente c=(Cliente)cliente.getSelectedItem();if(c==null){aviso("Selecciona un cliente.");return;}if(detalles.isEmpty()){aviso("Agrega al menos un producto al pedido.");return;}try{Pedido p=PedidoController.crearPedido((MetodoPago)metodo.getSelectedItem(),direccion.getText().trim());for(DetallePedido d:detalles.values())p.agregarDetalle(d);c.agregarPedido(p);mensaje("Pedido #"+p.getIdPedido()+" creado por "+String.format("$%,.0f",p.getTotal()));detalles.clear();refrescarCarrito();refrescarTabla();tabs.setSelectedIndex(1);}catch(Exception ex){aviso(ex.getMessage());}}
    private void pagarWompi(){int r=pedidos.getSelectedRow();if(r<0){aviso("Selecciona un pedido de la tabla.");return;}int id=(Integer)pedidosModel.getValueAt(r,0);Pedido p=PedidoController.buscarPedido(id);if(p==null||p.getTotal()<=0){aviso("El pedido no tiene un total válido para pago.");return;}try{String url=new AdaptadorPagoWompi().procesarPago(p.getTotal(),"PED-"+id);if(url==null)throw new IllegalStateException("No se pudo generar el enlace. Configura la llave sandbox WOMPI_PRIVATE_KEY.");JOptionPane.showMessageDialog(this,"Enlace de pago generado. Se abrirá en tu navegador.\n"+url);Desktop.getDesktop().browse(URI.create(url));}catch(Exception ex){aviso("Pago Wompi: "+ex.getMessage());}}
    public void refrescarClientes(){Object sel=cliente.getSelectedItem();cliente.removeAllItems();for(Cliente c:usuarios.listarClientes())cliente.addItem(c);if(sel!=null)cliente.setSelectedItem(sel);}
    public void refrescarProductos(){Producto sel=(Producto)producto.getSelectedItem();producto.removeAllItems();for(Producto p:ProductoController.listarProductos())if(p.isEstado())producto.addItem(p);if(sel!=null)producto.setSelectedItem(sel);}
    public void refrescarTabla(){pedidosModel.setRowCount(0);for(Pedido p:PedidoController.listarPedidos()){String clienteNom="-";for(Cliente c:usuarios.listarClientes())if(c.getPedidos().contains(p)){clienteNom=c.getNombre()+" "+c.getApellido();break;}pedidosModel.addRow(new Object[]{p.getIdPedido(),clienteNom,p.getTotal(),p.getEstado(),p.isPago()?"Sí":"No",p.getMetodoPago(),p.getFecha().format(F)});}}
    private void mensaje(String s){JOptionPane.showMessageDialog(this,s,"Pedidos",JOptionPane.INFORMATION_MESSAGE);}private void aviso(String s){JOptionPane.showMessageDialog(this,s,"Pedidos",JOptionPane.WARNING_MESSAGE);}
}