package view;

import controller.UsuarioController; import model.*;
import javax.swing.*; import javax.swing.table.DefaultTableModel; import java.awt.*; import java.time.LocalDate; import java.util.Date; import java.util.Optional;

/** Un solo flujo de alta: se elige Cliente/Empleado y el formulario se adapta. */
public class UsuarioPanel extends JPanel {
    private final UsuarioController controller; private final JComboBox<String> tipo=new JComboBox<>(new String[]{"Cliente","Empleado"});
    private final JTextField nombre=new JTextField(16),apellido=new JTextField(16),telefono=new JTextField(14),correo=new JTextField(20); private final JPasswordField password=new JPasswordField(16);
    private final JSpinner fechaNac=new JSpinner(new SpinnerDateModel(new Date(),null,null,java.util.Calendar.DAY_OF_MONTH));
    private final JComboBox<TipoCliente> tipoCliente=new JComboBox<>(TipoCliente.values()); private final JTextField direccion=new JTextField(20); private final JTextField cargo=new JTextField(16);
    private final JSpinner fechaContratacion=new JSpinner(new SpinnerDateModel(new Date(),null,null,java.util.Calendar.DAY_OF_MONTH)); private final CardLayout cards=new CardLayout(); private final JPanel especifico=new JPanel(cards);
    private final DefaultTableModel modelo=new DefaultTableModel(new Object[]{"ID","Tipo","Nombre","Teléfono","Correo","Detalle"},0){public boolean isCellEditable(int r,int c){return false;}}; private final JTable tabla=new JTable(modelo); private Integer idSeleccionado;
    public UsuarioPanel(UsuarioController controller){this.controller=controller;setLayout(new BorderLayout(12,12));setBorder(BorderFactory.createEmptyBorder(12,12,12,12));
        fechaNac.setEditor(new JSpinner.DateEditor(fechaNac,"dd/MM/yyyy"));fechaContratacion.setEditor(new JSpinner.DateEditor(fechaContratacion,"dd/MM/yyyy"));
        JPanel form=new JPanel(new GridBagLayout());form.setBorder(BorderFactory.createTitledBorder("Datos del usuario"));GridBagConstraints g=new GridBagConstraints();g.insets=new Insets(4,4,4,4);g.fill=GridBagConstraints.HORIZONTAL;
        add(form,g,0,"Tipo de usuario:",tipo);add(form,g,1,"Nombre:*",nombre);add(form,g,2,"Apellido:*",apellido);add(form,g,3,"Teléfono:*",telefono);add(form,g,4,"Correo:*",correo);add(form,g,5,"Contraseña:",password);add(form,g,6,"Fecha de nacimiento:",fechaNac);
        JPanel cliente=new JPanel(new GridLayout(2,2,5,5));cliente.add(new JLabel("Tipo de cliente:"));cliente.add(tipoCliente);cliente.add(new JLabel("Dirección:"));cliente.add(direccion);
        JPanel empleado=new JPanel(new GridLayout(2,2,5,5));empleado.add(new JLabel("Cargo:"));empleado.add(cargo);empleado.add(new JLabel("Fecha contratación:"));empleado.add(fechaContratacion);
        especifico.add(cliente,"Cliente");especifico.add(empleado,"Empleado");g.gridy=7;g.gridx=0;g.gridwidth=2;form.add(especifico,g);tipo.addActionListener(e->cards.show(especifico,(String)tipo.getSelectedItem()));cards.show(especifico,"Cliente");
        JPanel actions=new JPanel(new FlowLayout(FlowLayout.LEFT));JButton registrar=new JButton("Registrar usuario");JButton guardar=new JButton("Guardar cambios");JButton eliminar=new JButton("Eliminar");JButton limpiar=new JButton("Nuevo / limpiar");actions.add(registrar);actions.add(guardar);actions.add(eliminar);actions.add(limpiar);
        JPanel north=new JPanel(new BorderLayout());north.add(form,BorderLayout.CENTER);north.add(actions,BorderLayout.SOUTH);add(north,BorderLayout.NORTH);tabla.setRowHeight(25);add(new JScrollPane(tabla),BorderLayout.CENTER);add(new JLabel("La tabla se actualiza automáticamente; no hace falta un botón adicional de “listar usuarios”."),BorderLayout.SOUTH);
        registrar.addActionListener(e->registrar());guardar.addActionListener(e->editar());eliminar.addActionListener(e->eliminar());limpiar.addActionListener(e->limpiar());tabla.getSelectionModel().addListSelectionListener(e->cargar());refrescarTabla();
    }
    private LocalDate localDate(JSpinner s){return ((java.util.Date)s.getValue()).toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();}
    private void registrar(){if(!validar())return;Usuario u=construir(0);controller.agregarUsuario(u);mensaje("Usuario registrado con ID "+u.getIdUsuario());limpiar();refrescarTabla();}
    private Usuario construir(int id){String t=(String)tipo.getSelectedItem();LocalDate fn=localDate(fechaNac);String pass=new String(password.getPassword());if("Cliente".equals(t))return new Cliente(id,nombre.getText().trim(),apellido.getText().trim(),telefono.getText().trim(),correo.getText().trim(),pass,true,fn,0,(TipoCliente)tipoCliente.getSelectedItem(),direccion.getText().trim(),LocalDate.now());return new Empleado(id,nombre.getText().trim(),apellido.getText().trim(),telefono.getText().trim(),correo.getText().trim(),pass,true,fn,cargo.getText().trim(),(Date)fechaContratacion.getValue());}
    private boolean validar(){if(nombre.getText().isBlank()||apellido.getText().isBlank()||telefono.getText().isBlank()||correo.getText().isBlank()){aviso("Completa nombre, apellido, teléfono y correo.");return false;}if(idSeleccionado==null&&password.getPassword().length==0){aviso("La contraseña es obligatoria al registrar.");return false;}return true;}
    private void editar(){if(idSeleccionado==null){aviso("Selecciona un usuario de la tabla para editar.");return;}if(!validar())return;Usuario existente=controller.buscarPorId(idSeleccionado).orElse(null);if(existente==null)return;Usuario nuevo=construir(idSeleccionado);controller.actualizarUsuario(idSeleccionado,nuevo);mensaje("Cambios guardados.");refrescarTabla();}
    private void eliminar(){if(idSeleccionado==null){aviso("Selecciona un usuario para eliminar.");return;}if(JOptionPane.showConfirmDialog(this,"¿Eliminar al usuario seleccionado?","Confirmar",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){controller.eliminarUsuario(idSeleccionado);limpiar();refrescarTabla();}}
    private void cargar(){int r=tabla.getSelectedRow();if(r<0)return;idSeleccionado=(Integer)modelo.getValueAt(r,0);Optional<Usuario> op=controller.buscarPorId(idSeleccionado);if(op.isEmpty())return;Usuario u=op.get();nombre.setText(u.getNombre());apellido.setText(u.getApellido());telefono.setText(u.getTelefono());correo.setText(u.getCorreo());if(u.getFechaNacimiento()!=null) fechaNac.setValue(Date.from(u.getFechaNacimiento().atStartOfDay(java.time.ZoneId.systemDefault()).toInstant()));if(u instanceof Cliente c){tipo.setSelectedItem("Cliente");tipoCliente.setSelectedItem(c.getTipoCliente());direccion.setText(c.getDireccion());}else if(u instanceof Empleado e){tipo.setSelectedItem("Empleado");cargo.setText(e.getCargo());}}
    private void limpiar(){idSeleccionado=null;nombre.setText("");apellido.setText("");telefono.setText("");correo.setText("");password.setText("");direccion.setText("");cargo.setText("");tabla.clearSelection();}
    public void refrescarTabla(){modelo.setRowCount(0);for(Usuario u:controller.listarUsuarios()){String tipoU=u instanceof Cliente?"Cliente":"Empleado";String d=u instanceof Cliente c?c.getTipoCliente()+" · "+c.getDireccion():((Empleado)u).getCargo();modelo.addRow(new Object[]{u.getIdUsuario(),tipoU,u.getNombre()+" "+u.getApellido(),u.getTelefono(),u.getCorreo(),d});}}
    private void add(JPanel p,GridBagConstraints g,int y,String l,JComponent c){g.gridy=y;g.gridx=0;g.gridwidth=1;g.weightx=0;p.add(new JLabel(l),g);g.gridx=1;g.weightx=1;p.add(c,g);}private void mensaje(String s){JOptionPane.showMessageDialog(this,s,"Usuarios",JOptionPane.INFORMATION_MESSAGE);}private void aviso(String s){JOptionPane.showMessageDialog(this,s,"Usuarios",JOptionPane.WARNING_MESSAGE);}
}